# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b31408452e8115d98f36c5c6e2934453898d83d9b8a0e9d69457a756f85207a1f3b7952c95e227051f1205c6abda32e8fed9d82d57fe7a601a39140cb34281f8

test:
  secret_key_base: a0c4e764332de5f8687d291f26559d32845a06c7712e523ff4c07f3d1a1ac8bac4709fc49a2c5d03ed0039f2d440ecc7689e137741510a3863c1fcb6ac2d44c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
